application: govinspector
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /js
  static_dir: js

- url: /
  script: main.py

- url: /admin/addissue
  script: addissue.py